spring.application.name=shortURL

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USERNAME:default}
spring.data.redis.password=${REDIS_PASSWORD:}

app.host-url = ${APP_HOST_URL:http://localhost:8080}
app.snowflake.machine-id = ${APP_SNOWFLAKE_MACHINE_ID:1}